### ISSUE TITLE
Windows install error (can't find Python?)

### ISSUE THREAD

**Issue by ShiroKatake** [storj-thirdparty/uplink-nodejs#44]
Specs:
OS: Windows 10
MAKE: 0.8.1
NPM: 8.1.2
NODE: v16.3.0
NODE-GYP: v8.4.1
PYTHON: 3.10.2

Packages installed:
@types/node: ^17.0.10 (inside project)
node-gyp: 8.4.1 (globally)
make: 0.8.1 (globally)

Hello! I'm trying to follow this tutorial to install uplink-nodejs to my repo https://storj-thirdparty.github.io/uplink-nodejs/#/?id=initial-set-up-important, but I got the follow error.

```
error D:\GitHub\my-project\node_modules\uplink-nodejs: Command failed.
Exit code: 1
Command: (node-gyp configure) && (node-gyp rebuild)
Arguments:
Directory: D:\GitHub\my-project\node_modules\uplink-nodejs
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.13.0 | win32 | x64
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if the py launcher can be used to find Python
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (D:\GitHub\my-project\node_modules\node-gyp\lib\find-python.js:302:47)
gyp ERR! stack     at PythonFinder.runChecks (D:\GitHub\my-project\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\GitHub\my-project\node_modules\node-gyp\lib\find-python.js:200:18)
gyp ERR! stack     at PythonFinder.execFileCallback (D:\GitHub\my-project\node_modules\node-gyp\lib\find-python.js:266:16)
gyp ERR! stack     at exithandler (node:child_process:404:5)
gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:416:5)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
gyp ERR! stack     at onErrorNT (node:internal/child_process:477:16)
gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\GitHub\\my-project\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd D:\GitHub\my-project\node_modules\uplink-nodejs
gyp ERR! node -v v16.13.0
```

- I thought I needed to install Python, so I did, (v3.10.2), but that didn't work
- It suggested I might need to set `npm config` to the python path, which I did, and it still didn't work . . .
- I've made sure to set Path environment variable to libuplinkc*.* as well, which is $PROJECTROOT/node_modules/uplink-nodejs
![image](https://user-images.githubusercontent.com/54655740/150657843-836535af-1fec-4722-98ed-53300f7d4473.png)

Please ask if you need more info

**Comment by ShiroKatake** [comment]
Problem partially solved. According to this post, `node-gyp` only works with Python 2.7. Installed Python 2.7 and it now works, until it stopped because it can't find the files in `.....\node_modules\uplink-nodejs`

```
Warning: Missing input files:
D:\GitHub\my-project\node_modules\uplink-nodejs\uplink_definitions.h
D:\GitHub\my-project\node_modules\uplink-nodejs\libuplinkcv1.2.4.h
D:\GitHub\my-project\node_modules\uplink-nodejs\libuplinkcv1.2.4.dll
D:\GitHub\my-project\node_modules\uplink-nodejs\uplink_combat.h
```

I feel like I didn't do the environment variable step correctly . . . But how would it be able to use those files, if these would only be able to be used after being installed???

**Comment by ShiroKatake** [comment]
I noticed that where it says
```
Copying D:\GitHub\my-project\node_modules\uplink-nodejs/uplink_definitions.h
```
the path has a forward slash in there . . . I feel like that's where my problem might be. How can I fix that?

**Comment by bnn1** [comment]
Hello @ShiroKatake 
I had the same problem on linux because I didn't have Go installed.
After installing Go the problem was gone.

**Comment by bnn1** [comment]
@ShiroKatake tried restarting pc after installing go? also, did you do this step? 
> Set Path environment variable to libuplinkc*.* which is $PROJECTROOT/node_modules/uplink-nodejs

**Comment by ShiroKatake** [comment]
Yep, I've tried restarting. Also is the path environment variable step the 2nd image that I sent in the original post?

**Comment by kmozurkewich** [comment]
@ShiroKatake  - what is the output when you try executing "go" ?

**Comment by ShiroKatake** [comment]
it seems to be working fine
![image](https://user-images.githubusercontent.com/54655740/150875292-91c41558-1bb9-4990-a72b-98383e3c7d60.png)

**Comment by kmozurkewich** [comment]
Check the binding.gyp file, specifically https://github.com/storj-thirdparty/uplink-nodejs/blob/430b78f3c3cc98373f9aff55dc8dd8bd2e7fe7b4/binding.gyp#L23

You can try to update the path separator for your system and see if it makes a difference.  For some reason the build script cannot find that header file on your machine.

**Comment by ShiroKatake** [comment]
I'm sorry, how should I change it? I assume `<module_root_dir>` is the `uplink-nodejs` folder that got installed? In which case, these files don't exist in the directory . . .
![image](https://user-images.githubusercontent.com/54655740/150879114-a59e1909-a0e1-4d72-80d8-c6096ba24f87.png)

**Comment by khang-movember** [comment]
I've just realized this is similar to this open issue https://github.com/storj-thirdparty/uplink-nodejs/issues/37

**Comment by ShiroKatake** [comment]
Bumping post, I'm still stuck at this part. I still don't know how my package doesn't have these files to copy . . .

**Comment by ShiroKatake** [comment]
I read a few posts, notably [here](https://forum.storj.io/t/uplink-nodejs-will-not-run-on-windows/14434), and it looked like downgrading npm would seem to work. After downgrading it to `6.14.11`, the log messages look different, but the actual error still looks the same . . .
```
PS D:\GitHub\test> npm i uplink-nodejs

> uplink-nodejs@1.2.6 preinstall D:\GitHub\test\node_modules\uplink-nodejs
> make


  $ make <target...> [options]

  Options:
    --help             Show this help output
    --version          Show package version
    --debug            Enable extended log output

  Targets:
    GIT_REPO=https     Run target GIT_REPO=https
    build              Run target build
    clean              Run target clean

  Templates:
    ava                Generate ava setup (ava)
    cli                Generate cli setup (minimist, tabtab, ge...)
    default            Generate default setup (babel-cli, babel-plu...)
    eslint             Generate eslint setup (eslint, eslint-confi...)
    livereactload      Generate livereactload setup (babel-plugin-react-t...)
    mocha              Generate mocha setup (mocha)
    simple             Generate simple setup



> deasync@0.1.24 install D:\GitHub\test\node_modules\deasync
> node ./build.js

`win32-x64-node-16` exists; testing
Binary is fine; exiting

> uplink-nodejs@1.2.6 install D:\GitHub\test\node_modules\uplink-nodejs
> (node-gyp configure) && (node-gyp rebuild)


D:\GitHub\test\node_modules\uplink-nodejs>if not defined npm_config_node_gyp (node "C:\Users\tgkha\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure )  else (node "C:\Users\tgkha\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure )
(node:2644) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
Warning: Missing input files:
D:\GitHub\test\node_modules\uplink-nodejs\libuplinkcv1.2.4.dll
D:\GitHub\test\node_modules\uplink-nodejs\uplink_combat.h
D:\GitHub\test\node_modules\uplink-nodejs\uplink_definitions.h
D:\GitHub\test\node_modules\uplink-nodejs\libuplinkcv1.2.4.h

D:\GitHub\test\node_modules\uplink-nodejs>if not defined npm_config_node_gyp (node "C:\Users\tgkha\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\tgkha\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
(node:8616) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
Warning: Missing input files:
D:\GitHub\test\node_modules\uplink-nodejs\libuplinkcv1.2.4.dll
D:\GitHub\test\node_modules\uplink-nodejs\uplink_combat.h
D:\GitHub\test\node_modules\uplink-nodejs\uplink_definitions.h
D:\GitHub\test\node_modules\uplink-nodejs\libuplinkcv1.2.4.h
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  Copying D:\GitHub\test\node_modules\uplink-nodejs/uplink_combat.h to D:\GitHub\test\node_modules\uplink-nodejs/build/Release\uplink_combat.h
  The system cannot find the file specified.
  Copying D:\GitHub\test\node_modules\uplink-nodejs/libuplinkcversion.h to D:\GitHub\test\node_modules\uplink-nodejs/build/Release\libuplinkcversion.h
          1 file(s) copied.
  Copying D:\GitHub\test\node_modules\uplink-nodejs/libuplinkcv1.2.4.dll to D:\GitHub\test\node_modules\uplink-nodejs/build/Release\libuplinkcv1.2.4.dll
  The system cannot find the file specified.
  Copying D:\GitHub\test\node_modules\uplink-nodejs/libuplinkcv1.2.4.h to D:\GitHub\test\node_modules\uplink-nodejs/build/Release\libuplinkcv1.2.4.h
  The system cannot find the file specified.
  Copying D:\GitHub\test\node_modules\uplink-nodejs/uplink_definitions.h to D:\GitHub\test\node_modules\uplink-nodejs/build/Release\uplink_definitions.h
  The system cannot find the file specified.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8064: Custom build for item "D:\GitHub\test\node_modules\uplink-nodejs\uplink_combat.h" su 
cceeded, but specified dependency "d:\github\test\node_modules\uplink-nodejs\uplink_combat.h" does not exist. This may cause incremental build to work incorrectly. [D:\GitHub\test\node_modules\uplink-nodejs\build\uplink.vcxpr 
oj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8065: Custom build for item "D:\GitHub\test\node_modules\uplink-nodejs\uplink_combat.h" su 
cceeded, but specified output "d:\github\test\node_modules\uplink-nodejs\build\release\uplink_combat.h" has not been created. This may cause incremental build to work incorrectly. [D:\GitHub\test\node_modules\uplink-nodejs\bu 
ild\uplink.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8064: Custom build for item "D:\GitHub\test\node_modules\uplink-nodejs\libuplinkcv1.2.4.dl 
l" succeeded, but specified dependency "d:\github\test\node_modules\uplink-nodejs\libuplinkcv1.2.4.dll" does not exist. This may cause incremental build to work incorrectly. [D:\GitHub\test\node_modules\uplink-nodejs\build\up 
link.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8065: Custom build for item "D:\GitHub\test\node_modules\uplink-nodejs\libuplinkcv1.2.4.dl 
l" succeeded, but specified output "d:\github\test\node_modules\uplink-nodejs\build\release\libuplinkcv1.2.4.dll" has not been created. This may cause incremental build to work incorrectly. [D:\GitHub\test\node_modules\uplink 
-nodejs\build\uplink.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8064: Custom build for item "D:\GitHub\test\node_modules\uplink-nodejs\libuplinkcv1.2.4.h" 
 succeeded, but specified dependency "d:\github\test\node_modules\uplink-nodejs\libuplinkcv1.2.4.h" does not exist. This may cause incremental build to work incorrectly. [D:\GitHub\test\node_modules\uplink-nodejs\build\uplink
.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8065: Custom build for item "D:\GitHub\test\node_modules\uplink-nodejs\libuplinkcv1.2.4.h" 
 succeeded, but specified output "d:\github\test\node_modules\uplink-nodejs\build\release\libuplinkcv1.2.4.h" has not been created. This may cause incremental build to work incorrectly. [D:\GitHub\test\node_modules\uplink-nod 
ejs\build\uplink.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8064: Custom build for item "D:\GitHub\test\node_modules\uplink-nodejs\uplink_definitions. 
h" succeeded, but specified dependency "d:\github\test\node_modules\uplink-nodejs\uplink_definitions.h" does not exist. This may cause incremental build to work incorrectly. [D:\GitHub\test\node_modules\uplink-nodejs\build\up 
link.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8065: Custom build for item "D:\GitHub\test\node_modules\uplink-nodejs\uplink_definitions. 
h" succeeded, but specified output "d:\github\test\node_modules\uplink-nodejs\build\release\uplink_definitions.h" has not been created. This may cause incremental build to work incorrectly. [D:\GitHub\test\node_modules\uplink 
-nodejs\build\uplink.vcxproj]
  libUplink_win.cc
  promises_execute_win.cc
  promises_complete_win.cc
  project_operations_win.cc
  download_operations_win.cc
  upload_operations_win.cc
  access_operations_win.cc
  bucket_operations_win.cc
  object_operations_win.cc
  win_delay_load_hook.cc
D:\GitHub\test\node_modules\uplink-nodejs\functions_win\definitions_win.h(13,10): fatal error C1083: Cannot open include file: '../uplink_definitions.h': No such file or directory (compiling source file ..\functions_win\uploa
d_operations_win.cc) [D:\GitHub\test\node_modules\uplink-nodejs\build\uplink.vcxproj]
D:\GitHub\test\node_modules\uplink-nodejs\functions_win\definitions_win.h(13,10): fatal error C1083: Cannot open include file: '../uplink_definitions.h': No such file or directory (compiling source file ..\functions_win\promi 
ses_execute_win.cc) [D:\GitHub\test\node_modules\uplink-nodejs\build\uplink.vcxproj]
D:\GitHub\test\node_modules\uplink-nodejs\functions_win\definitions_win.h(13,10): fatal error C1083: Cannot open include file: '../uplink_definitions.h': No such file or directory (compiling source file ..\functions_win\proje 
ct_operations_win.cc) [D:\GitHub\test\node_modules\uplink-nodejs\build\uplink.vcxproj]
D:\GitHub\test\node_modules\uplink-nodejs\functions_win\definitions_win.h(13,10): fatal error C1083: Cannot open include file: '../uplink_definitions.h': No such file or directory (compiling source file ..\functions_win\promi 
ses_complete_win.cc) [D:\GitHub\test\node_modules\uplink-nodejs\build\uplink.vcxproj]
D:\GitHub\test\node_modules\uplink-nodejs\functions_win\definitions_win.h(13,10): fatal error C1083: Cannot open include file: '../uplink_definitions.h': No such file or directory (compiling source file ..\libUplink_win.cc) [ 
D:\GitHub\test\node_modules\uplink-nodejs\build\uplink.vcxproj]
D:\GitHub\test\node_modules\uplink-nodejs\functions_win\definitions_win.h(13,10): fatal error C1083: Cannot open include file: '../uplink_definitions.h': No such file or directory (compiling source file ..\functions_win\downl
oad_operations_win.cc) [D:\GitHub\test\node_modules\uplink-nodejs\build\uplink.vcxproj]
D:\GitHub\test\node_modules\uplink-nodejs\functions_win\definitions_win.h(13,10): fatal error C1083: Cannot open include file: '../uplink_definitions.h': No such file or directory (compiling source file ..\functions_win\bucke 
t_operations_win.cc) [D:\GitHub\test\node_modules\uplink-nodejs\build\uplink.vcxproj]
D:\GitHub\test\node_modules\uplink-nodejs\functions_win\definitions_win.h(13,10): fatal error C1083: Cannot open include file: '../uplink_definitions.h': No such file or directory (compiling source file ..\functions_win\objec 
t_operations_win.cc) [D:\GitHub\test\node_modules\uplink-nodejs\build\uplink.vcxproj]
D:\GitHub\test\node_modules\uplink-nodejs\functions_win\definitions_win.h(13,10): fatal error C1083: Cannot open include file: '../uplink_definitions.h': No such file or directory (compiling source file ..\functions_win\acces 
s_operations_win.cc) [D:\GitHub\test\node_modules\uplink-nodejs\build\uplink.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\tgkha\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\tgkha\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\GitHub\test\node_modules\uplink-nodejs
gyp ERR! node -v v16.13.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\@parcel\watcher\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uplink-nodejs@1.2.6 install: `(node-gyp configure) && (node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uplink-nodejs@1.2.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tgkha\AppData\Roaming\npm-cache\_logs\2022-01-30T11_42_39_091Z-debug.log
```

**Comment by ShiroKatake** [comment]
More bumps

**Comment by scottie** [comment]
BUMP! https://github.com/storj-thirdparty/uplink-nodejs/issues/53

@ShiroKatake I do not know why companies pretend that they offer other language implementations when its just a wrapper, our only option is to use GO not sure why they do not make a native JS implementation if so Storj would be a lot more utilized in the world. Rather frustrating to be honest.

**Comment by kmozurkewich** [comment]
@ShiroKatake  - this may help - https://forum.storj.io/t/create-access-grant-with-storj-api/18290/12

Looks like the missing header issue from above is from something in the build scripts.

**Comment by ShiroKatake** [comment]
Thanks guys, is it normal that the `make` command in `preinstall` doesn't do anything? It looks like there's supposed to be some sort of parameter being passed into it . . .

**Comment by kmozurkewich** [comment]
@ShiroKatake  - there should be a build step that make performs - no parameter just means "use the makefile in the local dir"
