### ISSUE TITLE
Uplink module installation failure in ubuntu 22.04

### ISSUE THREAD

**Issue by rishmalkp** [storj-thirdparty/uplink-nodejs#64]
`npm install uplink-nodejs`

npm ERR! code 7
npm ERR! path /home/reileigh/node_modules/uplink-nodejs
npm ERR! command failed
npm ERR! command sh -c (node-gyp configure) && (node-gyp rebuild)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@21.6.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.10.6 found at "/usr/bin/python3"
npm ERR! (node:16769) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp ERR! UNCAUGHT EXCEPTION 
npm ERR! gyp ERR! stack TypeError: Cannot assign to read only property 'cflags' of object '#<Object>'
npm ERR! gyp ERR! stack     at createConfigFile (/home/reileigh/node_modules/node-gyp/lib/configure.js:117:21)
npm ERR! gyp ERR! stack     at /home/reileigh/node_modules/node-gyp/lib/configure.js:84:9
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:194:23)
npm ERR! gyp ERR! System Linux 5.19.0-38-generic
npm ERR! gyp ERR! command "/usr/local/bin/node" "/home/reileigh/node_modules/.bin/node-gyp" "configure"
npm ERR! gyp ERR! cwd /home/reileigh/node_modules/uplink-nodejs
npm ERR! gyp ERR! node -v v21.6.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! Node-gyp failed to build your package.
npm ERR! gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.

**Comment by Devleed** [comment]
I'm facing same issue.
